language: python
dist: trusty
cache: pip
python:
  - 2.7
before_install:
 - sudo apt-get install -qq python-numpy python-scipy
install:
  - pip install -r requirements.txt
script:
  - ./test/scripts/unit_tests.sh
  - ./stream_alert_cli.py lambda test --processor all
after_success:
  coveralls
